# CMAKE generated file: DO NOT EDIT!
# Generated by "MinGW Makefiles" Generator, CMake Version 4.0

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

SHELL = cmd.exe

# The CMake executable.
CMAKE_COMMAND = "C:\Program Files\CMake\bin\cmake.exe"

# The command to remove a file.
RM = "C:\Program Files\CMake\bin\cmake.exe" -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = D:\OOP\Lab\OOP

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = D:\OOP\Lab\OOP

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	"C:\Program Files\CMake\bin\cmake-gui.exe" -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	"C:\Program Files\CMake\bin\cmake.exe" --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start D:\OOP\Lab\OOP\CMakeFiles D:\OOP\Lab\OOP\\CMakeFiles\progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start D:\OOP\Lab\OOP\CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named ShoppingSystem

# Build rule for target.
ShoppingSystem: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 ShoppingSystem
.PHONY : ShoppingSystem

# fast build rule for target.
ShoppingSystem/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\ShoppingSystem.dir\build.make CMakeFiles/ShoppingSystem.dir/build
.PHONY : ShoppingSystem/fast

src/Goods.obj: src/Goods.cpp.obj
.PHONY : src/Goods.obj

# target to build an object file
src/Goods.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\ShoppingSystem.dir\build.make CMakeFiles/ShoppingSystem.dir/src/Goods.cpp.obj
.PHONY : src/Goods.cpp.obj

src/Goods.i: src/Goods.cpp.i
.PHONY : src/Goods.i

# target to preprocess a source file
src/Goods.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\ShoppingSystem.dir\build.make CMakeFiles/ShoppingSystem.dir/src/Goods.cpp.i
.PHONY : src/Goods.cpp.i

src/Goods.s: src/Goods.cpp.s
.PHONY : src/Goods.s

# target to generate assembly for a file
src/Goods.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\ShoppingSystem.dir\build.make CMakeFiles/ShoppingSystem.dir/src/Goods.cpp.s
.PHONY : src/Goods.cpp.s

src/Order.obj: src/Order.cpp.obj
.PHONY : src/Order.obj

# target to build an object file
src/Order.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\ShoppingSystem.dir\build.make CMakeFiles/ShoppingSystem.dir/src/Order.cpp.obj
.PHONY : src/Order.cpp.obj

src/Order.i: src/Order.cpp.i
.PHONY : src/Order.i

# target to preprocess a source file
src/Order.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\ShoppingSystem.dir\build.make CMakeFiles/ShoppingSystem.dir/src/Order.cpp.i
.PHONY : src/Order.cpp.i

src/Order.s: src/Order.cpp.s
.PHONY : src/Order.s

# target to generate assembly for a file
src/Order.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\ShoppingSystem.dir\build.make CMakeFiles/ShoppingSystem.dir/src/Order.cpp.s
.PHONY : src/Order.cpp.s

src/ShoppingSystem.obj: src/ShoppingSystem.cpp.obj
.PHONY : src/ShoppingSystem.obj

# target to build an object file
src/ShoppingSystem.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\ShoppingSystem.dir\build.make CMakeFiles/ShoppingSystem.dir/src/ShoppingSystem.cpp.obj
.PHONY : src/ShoppingSystem.cpp.obj

src/ShoppingSystem.i: src/ShoppingSystem.cpp.i
.PHONY : src/ShoppingSystem.i

# target to preprocess a source file
src/ShoppingSystem.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\ShoppingSystem.dir\build.make CMakeFiles/ShoppingSystem.dir/src/ShoppingSystem.cpp.i
.PHONY : src/ShoppingSystem.cpp.i

src/ShoppingSystem.s: src/ShoppingSystem.cpp.s
.PHONY : src/ShoppingSystem.s

# target to generate assembly for a file
src/ShoppingSystem.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\ShoppingSystem.dir\build.make CMakeFiles/ShoppingSystem.dir/src/ShoppingSystem.cpp.s
.PHONY : src/ShoppingSystem.cpp.s

src/User.obj: src/User.cpp.obj
.PHONY : src/User.obj

# target to build an object file
src/User.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\ShoppingSystem.dir\build.make CMakeFiles/ShoppingSystem.dir/src/User.cpp.obj
.PHONY : src/User.cpp.obj

src/User.i: src/User.cpp.i
.PHONY : src/User.i

# target to preprocess a source file
src/User.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\ShoppingSystem.dir\build.make CMakeFiles/ShoppingSystem.dir/src/User.cpp.i
.PHONY : src/User.cpp.i

src/User.s: src/User.cpp.s
.PHONY : src/User.s

# target to generate assembly for a file
src/User.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\ShoppingSystem.dir\build.make CMakeFiles/ShoppingSystem.dir/src/User.cpp.s
.PHONY : src/User.cpp.s

src/main.obj: src/main.cpp.obj
.PHONY : src/main.obj

# target to build an object file
src/main.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\ShoppingSystem.dir\build.make CMakeFiles/ShoppingSystem.dir/src/main.cpp.obj
.PHONY : src/main.cpp.obj

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\ShoppingSystem.dir\build.make CMakeFiles/ShoppingSystem.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\ShoppingSystem.dir\build.make CMakeFiles/ShoppingSystem.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

# Help Target
help:
	@echo The following are some of the valid targets for this Makefile:
	@echo ... all (the default if no target is provided)
	@echo ... clean
	@echo ... depend
	@echo ... edit_cache
	@echo ... rebuild_cache
	@echo ... ShoppingSystem
	@echo ... src/Goods.obj
	@echo ... src/Goods.i
	@echo ... src/Goods.s
	@echo ... src/Order.obj
	@echo ... src/Order.i
	@echo ... src/Order.s
	@echo ... src/ShoppingSystem.obj
	@echo ... src/ShoppingSystem.i
	@echo ... src/ShoppingSystem.s
	@echo ... src/User.obj
	@echo ... src/User.i
	@echo ... src/User.s
	@echo ... src/main.obj
	@echo ... src/main.i
	@echo ... src/main.s
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 0
.PHONY : cmake_check_build_system

